<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <NoWarn>1701;1702;1591</NoWarn>
    <OutputType>Exe</OutputType>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SysWeaver\SysWeaver.CommandLine\SysWeaver.CommandLine.csproj" />
    <ProjectReference Include="..\..\SysWeaver\SysWeaver.Common\SysWeaver.Common.csproj" />
    <ProjectReference Include="..\..\SysWeaver\SysWeaver.Compression\SysWeaver.Compression.csproj" />
    <ProjectReference Include="..\..\SysWeaver\SysWeaver.FolderSync\SysWeaver.FolderSync.csproj" />
    <ProjectReference Include="..\..\SysWeaver\SysWeaver.Storage.Cdc\SysWeaver.Storage.Cdc.csproj" />
  </ItemGroup>

</Project>
