<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetFramework>net8.0</TargetFramework>
	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
	  <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SysWeaver\SysWeaver.CommandLine\SysWeaver.CommandLine.csproj" />
    <ProjectReference Include="..\..\SysWeaver\SysWeaver.FolderSync\SysWeaver.FolderSync.csproj" />
  </ItemGroup>

</Project>
