<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
	  <NoWarn>1701;1702;1591</NoWarn>	  
	  <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
